#!/bin/bash
#
# This script builds the Android release package.

set -e

source $(dirname $0)/library
version=$(wc_read_version)

pushd android
./gradlew assembleRelease
cp Dakarwalletcore/build/outputs/aar/Dakarwalletcore-release.aar ../build/Dakarwalletcore.aar
popd

echo "Now upload build/Dakarwalletcore.aar to https://github.com/DakarWallet/Dakar-wallet-core/releases/tag/$version"
