#!/bin/bash
#
# This script runs the iOS tests.

set -e

pushd swift
xcodegen
pod install
fastlane scan --workspace DakarWalletCore.xcworkspace --scheme DakarWalletCore --sdk iphonesimulator --device='iPhone 11' --clean
popd
